# Generated by Django 3.2.25 on 2024-04-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200211_1303'),
        ('products', '0002_auto_20240414_2339'),
    ]

    operations = [
    ]
